### ISSUE TITLE
Tracking Issue: Beepberry Computer v0.1

### ISSUE THREAD

**Issue by jamesmunns** [tosc-rs/mnemos#71]
CC @hawkw, this is just a running list for "it's a computer" feature completeness on the beepberry, in no particular order

* [x] Restore the the SPI driver from `james/add-sharp-display` (I forgot to grab this in #69 
    * [x] Open as #72 
* [x] Move the `EmbGraphics` driver definition from melpo to the kernel
    * [x] Open as #75 
* [x] Implement the `EmbGraphics` driver on top of the SPI port for `lichee-rv`
    * [x] Implemented in #114 
* [x] Write an I2C driver for the D1, and create some kind of service interface for it
  * [x] I2C service definition: #101 
  * [x] D1 I2C driver: #102 
* [x] Integrate https://github.com/jamesmunns/bbq10kbd, on top of the driver service
    * [x] Figure out if there are any changes necessary for sqfmi's fork of the keyboard firmware
* [x] Make a new `platform/allwinner-d1/boards/mq-pro` project, make sure everything from `lichee-rv` still works there.
    * UART and SPI are mapped the same, likely only LED and other trivial things need to be changed 
    * Implemented in #112 

I *think* these are all the "must dos" to have a standalone computer. From there, we can either start cleaning up some "nice to haves", or start figuring out what to build next

**Comment by jamesmunns** [comment]
Did a quick cross check of pinouts on the Pi/lichee-rv/mangopi mq-pro [on a spreadsheet](https://docs.google.com/spreadsheets/d/1XbbXARVXu009ZRdzl69T0_YmjL-_Ab0TnPQSrKdww2I/edit?usp=sharing).

Looks like the same SPI pins are used for the display, so no changes to the code in #72 should be necessary.

UART0 is also brought out to the same pins as the standard RPI UART TX/RX:

![Screenshot 2023-06-20 at 13-38-54 GPIO 14 (UART Transmit) at Raspberry Pi GPIO Pinout](https://github.com/tosc-rs/mnemos/assets/2097964/a24ff7a2-5c82-4e48-b20d-46ffbc17ae63)

**Comment by jamesmunns** [comment]
Unfortunately the I2C lines available on the MQ-Pro (PG12/PG13) are not brought out on the Sipeed board (PB0/PB1 are used instead).

PG12/13 are mapped to TWI0 (and also UART1).
PB0/1 are mapped to TWI2 (and also UART2).

Interestingly enough, it looks like we could remap the I2C to UART, the RP2040 has a matching UART pair on the same pins as SDA. This could be useful for higher bandwidth comms.

**Comment by jamesmunns** [comment]
Also of note: The Mango Pi PTH are too small to work with the pogo pins on the beepberry. For now, I have designed a small adapter board that will give us space to mount the mango pi, and also additional breakout pins for testing. It should arrive around 2023-06-23 or so for testing.

![Screenshot 2023-06-17 at 22-45-49 Sandbox _ mnemos-shield-mini by James on AISLER](https://github.com/tosc-rs/mnemos/assets/2097964/6818ce7a-6f7a-459d-b375-b066a6c7d4cc)

In the long term, it might be better to design our own board based on a sipeed lichee-rv SOM.

I found [this project](https://github.com/riktw/jeadock) which has already done this to breakout ethernet capabilities, we can likely re-use their pinout/sizing.

Making a new board will also let us do a couple things that are interesting:

* Using a different (less of a pain in the ass) wifi chip, like an esp32c3
* Breakout the onboard headphone/mic audio I/O
* Use other IO available (RPI header is limited to 40 pins, sipeed SOM has 134 pins, both are a mix of I/O and power)

**Comment by hawkw** [comment]
@jamesmunns are you currently working on the I2C driver? If not, I'd be happy to pick it up.

**Comment by jamesmunns** [comment]
@hawkw not yet! Very happy to have you work on it. Let me know if you need/want help with anything.

**Comment by hawkw** [comment]
as of #155 and #158, the keyboard works and is glued onto the Forth shell, so i think we can call this one finished! 🎉🎉🎉
